### PR TITLE
installed-files: Indicate when .a files can be removed in install

### PR DESCRIPTION
**Pull request by mgorny**
Signed-off-by: Michał Górny <mgorny@gentoo.org>

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/qa

**Review by SoapGentoo — APPROVED** [review]

**Comment by mgorny** [comment]
Ping.

**Review by Zlogene — APPROVED** [review]

**Comment by ulm** [comment]
Looks a little too much like micro-management. The policy is clear, and I think it could be left to the maintainer how they achieve this goal.

**Comment by SoapGentoo** [comment]
It's a note, not a directive

**Review by thesamesam — APPROVED** [review]

**Pull request closed without merging**
